wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.4
    t:
      4: 3.9.4
      5: 0.10.21
      8:
      - 5
input_artifact:
  desc: null
  value: sample.csv:latest
max_price:
  desc: null
  value: 350.0
min_price:
  desc: null
  value: 10.0
output_description:
  desc: null
  value: Data with outliers and null values removed
output_name:
  desc: null
  value: clean_sample.csv
output_type:
  desc: null
  value: clean_sample
